on:
  push:
    branches:
      - main

jobs:
  build-resume:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: 'write'
      pull-requests: 'read'

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build docker image
        run: make build

      - name: Push docker image
        run: make push

      - name: Build resume
        run: make build-resume

      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          prerelease: false
          automatic_release_tag: latest
          files: |
            resume.pdf
